version: '3.7'

services:
  indypool:
    build:
      context: . 
      dockerfile: indy-pool.dockerfile
      args:
        pool_ip: '10.0.0.2'
    init: true
    container_name: tykn_indy_pool
    ports:
      - "9701:9701"
      - "9702:9702"
      - "9703:9703"
      - "9704:9704"
      - "9705:9705"
      - "9706:9706"
      - "9707:9707"
      - "9708:9708"
    networks:
      pool_network:
        ipv4_address: 10.0.0.2
  tyknims:
    build: 
      context: TyknIMS  
      dockerfile: Dockerfile
    init: true
    container_name: tyknims
    ports:
      - "50001:50001"
    networks:
      pool_network:
        ipv4_address: 10.0.0.3
    links:
      - indypool
  orgims:
    build:
      context: OrgIMS  
      dockerfile: Dockerfile
    init: true
    container_name: orgims
    ports:
      - "50002:50002"
    networks:
      pool_network:
        ipv4_address: 10.0.0.4
    links:
      - indypool
      - tyknims
  userims:
    build: 
      context: UserIMS 
      dockerfile: Dockerfile
    init: true
    container_name: userims
    ports:
      - "50003:50003"
    networks:
      pool_network:
        ipv4_address: 10.0.0.5
    links:
      - indypool

networks:
  pool_network:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 10.0.0.0/24